#!/usr/bin/env bash
#
# Pinegrap - Enterprise Website Platform
#
# Brings up a throwaway Pinegrap instance inside an ephemeral sandbox so a
# runtime bug can be reproduced. It touches nothing outside the sandbox: a
# local MariaDB, a local database, a generated data/config.php and PHP's
# built-in server on 127.0.0.1.
#
# Do NOT run this on a development machine or a live site: it overwrites
# pinegrap/data/config.php and drops the database it creates.
#
# Usage:  bash tools/setup_sandbox.sh [port]        (default port: 8000)
#
# @author      Erdal Güral (Kodpen)
# @link        https://kodpen.com
# @copyright   2017–2026 Kodpen
# @license     https://opensource.org/licenses/mit-license.html MIT License

set -euo pipefail

PORT="${1:-8000}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEB_ROOT="$ROOT/pinegrap"
CONFIG_FILE="$WEB_ROOT/data/config.php"

DB_NAME="pinegrap_sandbox"
DB_USER="pinegrap"
DB_PASSWORD="sandbox"

ADMIN_USER="admin"
ADMIN_PASSWORD="sandbox-admin"
ADMIN_EMAIL="admin@example.test"

BASE_URL="http://127.0.0.1:$PORT"

say() { printf '\n== %s\n' "$1"; }

if [ ! -d "$WEB_ROOT" ]; then
	echo "Product tree not found at $WEB_ROOT - run this from the repository." >&2
	exit 1
fi

# Root is expected: the sandbox runs as root, a workstation does not.
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
	if command -v sudo >/dev/null 2>&1; then
		SUDO="sudo"
	else
		echo "This script needs root to install and start MariaDB." >&2
		exit 1
	fi
fi

say "Installing MariaDB and the PHP extensions Pinegrap needs"

export DEBIAN_FRONTEND=noninteractive

$SUDO apt-get update -qq
$SUDO apt-get install -y -qq mariadb-server php-mysqli php-gd php-mbstring php-curl php-zip php-xml >/dev/null

say "Starting MariaDB"

# Depending on the image either service or mysqld_safe is the way in.
$SUDO service mariadb start >/dev/null 2>&1 || $SUDO service mysql start >/dev/null 2>&1 || {
	$SUDO mkdir -p /var/run/mysqld /var/lib/mysql
	$SUDO chown -R mysql:mysql /var/run/mysqld /var/lib/mysql
	$SUDO mysqld_safe --skip-grant-tables=0 >/dev/null 2>&1 &
}

for _ in $(seq 1 30); do
	if $SUDO mysqladmin ping >/dev/null 2>&1; then
		break
	fi
	sleep 1
done

$SUDO mysqladmin ping >/dev/null 2>&1 || { echo "MariaDB did not come up." >&2; exit 1; }

say "Creating the database and its user"

$SUDO mysql <<SQL
DROP DATABASE IF EXISTS \`$DB_NAME\`;
CREATE DATABASE \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
SQL

say "Writing data/config.php"

# The installer refuses to run against a config that already holds a version,
# so the file is written with connection details only. The encryption key is
# generated per sandbox and never reused anywhere else.
ENCRYPTION_KEY="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Z0-9' | head -c 32)"

cat > "$CONFIG_FILE" <<PHP
<?php
// Generated by tools/setup_sandbox.sh for a throwaway sandbox instance.
if (php_sapi_name() != 'cli' && !defined('CONFIG_FILE_PATH')) {
	http_response_code(403);
	exit("Forbidden");
}
define('DB_HOST', 'localhost');
define('DB_USERNAME', '$DB_USER');
define('DB_PASSWORD', '$DB_PASSWORD');
define('DB_DATABASE', '$DB_NAME');
define('ENCRYPTION_KEY', '$ENCRYPTION_KEY');
define('DEFAULT_SOFTWARE_LANGUAGE', 'tr');
define('ENVIRONMENT', 'development');
?>
PHP

say "Starting PHP's built-in server on $BASE_URL"

php -S "127.0.0.1:$PORT" -t "$WEB_ROOT" >/tmp/pinegrap-server.log 2>&1 &
SERVER_PID=$!

for _ in $(seq 1 20); do
	if curl -fsS -o /dev/null "$BASE_URL/install/" 2>/dev/null; then
		break
	fi
	sleep 1
done

if ! kill -0 "$SERVER_PID" 2>/dev/null; then
	echo "The PHP server exited. See /tmp/pinegrap-server.log" >&2
	exit 1
fi

say "Running the installer"

# The schema is built by the migration runner, which only the installer drives;
# there is no SQL dump of a complete install to load instead. The wizard is a
# plain form, so it is posted here with a CSRF token taken from the page.
COOKIES="$(mktemp)"

TOKEN="$(curl -fsS -c "$COOKIES" "$BASE_URL/install/" \
	| grep -oE "name=\"token\" value=\"[^\"]+\"" \
	| head -1 \
	| sed -E 's/.*value="([^"]+)".*/\1/')"

if [ -z "$TOKEN" ]; then
	echo "Could not read the installer's CSRF token - the install page may have changed." >&2
	echo "The database, config.php and the server at $BASE_URL are ready; finish the wizard by hand." >&2
	exit 2
fi

RESPONSE="$(curl -fsS -b "$COOKIES" -c "$COOKIES" \
	-d "token=$TOKEN" \
	-d "install=true" \
	-d "db_host=localhost" \
	-d "db_username=$DB_USER" \
	-d "db_password=$DB_PASSWORD" \
	-d "db_database=$DB_NAME" \
	-d "admin_username=$ADMIN_USER" \
	-d "admin_password=$ADMIN_PASSWORD" \
	-d "admin_confirm_password=$ADMIN_PASSWORD" \
	-d "admin_email_address=$ADMIN_EMAIL" \
	-d "admin_confirm_email_address=$ADMIN_EMAIL" \
	-d "default_software_language=tr" \
	-d "software_update_check=false" \
	-d "send_email=false" \
	"$BASE_URL/install/" || true)"

# The schema is the only honest proof that the install worked.
TABLE_COUNT="$($SUDO mysql -N -B -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '$DB_NAME';")"

if [ "$TABLE_COUNT" -lt 50 ]; then
	echo "The installer did not build the schema (only $TABLE_COUNT table(s) exist)." >&2
	echo "Its response is in /tmp/pinegrap-install.html; the server is still running at $BASE_URL/install/." >&2
	printf '%s' "$RESPONSE" > /tmp/pinegrap-install.html
	exit 2
fi

say "Ready"

cat <<INFO
Site        $BASE_URL
Panel       $BASE_URL/ (sign in as $ADMIN_USER / $ADMIN_PASSWORD)
Database    $DB_NAME as $DB_USER / $DB_PASSWORD ($TABLE_COUNT tables)
Server log  /tmp/pinegrap-server.log (PID $SERVER_PID)

Everything here lives and dies with this sandbox.
INFO
